### ISSUE TITLE
compatibility error with the cat command

### ISSUE THREAD

**Issue by microSoftware** [stpe/mixpanel-engage-post#1]
Hello,

I generated a json file to delete some users. (there are 2 id).

This command : `cat id-to-delete.json > node engagepost.js -k myKey -s mySecretKey -t myToken`
return an error :

> cat: -k: No such file or directory
> cat: mykey No such file or directory
> cat: -s: No such file or directory
> cat: mySecretKey: No such file or directory
> cat: -t: No such file or directory
> cat: myToken: No such file or directory

If i do with the command : less.

I have no error but none of my users are deleted.

I look up, my 2 id i want to delete are well on Mixpanel.

And...here how is my id-to-delete.json :
`
[
  {
    "$distinct_id": "59e6a7a1",
    "$delete": ""
  },
  {
    "$distinct_id": "0bbdc673",
    "$delete": ""
  }
]
`

And I tried to write down my key, secretKey and token in a .env file (in the same folder than engagepost.js) like thus :

MIXPANEL_API_KEY=myKey
MIXPANEL_API_SECRET=mySecretKey
MIXPANEL_API_TOKEN=myToken

No error again...but none of my users are deleted.

Any idea ?

Thanks

**Comment by stpe** [comment]
When piping your json file, test doing it using `|` (pipe-character), i.e.:

`cat id-to-delete.json | node engagepost.js -k myKey -s mySecretKey -t myToken`

Does it work now, @microSoftware?

**Comment by microSoftware** [comment]
Yes it's perfect. Thanks stpe
